### ISSUE TITLE
書類の却下機能

### ISSUE THREAD

**Issue by suzukikaito244** [nkc-cta20-team3/Student-Support-System-reserve#101]

**Comment by Naga564** [comment]
# やるべきこと

- ドキュメント
    - 仕様を決める必要がある
- フロント
    - ボタンを押されたときの処理を分ける
- バックエンド
    - 却下するAPIが必要
    - もしくは、認可するAPI(UpdateAuth)の拡張

**Comment by Naga564** [comment]
仕様を決めたドキュメントを作成・共有する必要があります
もし、時間が足りないのであれば手伝います。

**Comment by suzukikaito244** [comment]
APIの実装はおわりました

**Comment by Naga564** [comment]
# 追加のやるべきこと
- 全体での方針
  - 通知機能を入れる際に使うので、教員コメントも更新できるようにする
- フロントエンド
  - API変更の必要があるのでそれに対応させる
    - APIに渡す引数を追加する
    - 担任コメントの入力チェックを行い、適切な条件でAPIを呼び出す
- バックエンド
  - Rejection APIの名前を変更する(RejectAuth)
  - APIの修正
    - 教員コメントも引数に取る
    - 教員コメントを更新する
    - 担任の場合のみ、教員コメントを更新する
