### ISSUE TITLE
学生と教員の判別機能の実装

### ISSUE THREAD

**Issue by magic178** [nkc-cta20-team3/Student-Support-System-reserve#103]

**Comment by Naga564** [comment]
# 変更すべき要素

- ドキュメント
  - データベースの構造を変える必要がある
- フロント
  -firebaseから受け取ったデータをもとに識別するAPIを呼び出す
- バック
  - 教員か学生かを識別するAPIを実装する
- その他
  - 後回しにして、パスワードとメールアドレスで認証する方式にするという手もある
    - firebaseで実現できる

**Comment by Naga564** [comment]
# 予定(仮)
## データベース
- 4/27までに形を決める(DB担当者と)
- その後DB担当者、AWS担当者に話を通す

**Comment by Naga564** [comment]
データベース完了

**Comment by Naga564** [comment]
# API設計

## GetPosition
### 引数
| 引数名 | 型 |
| --- | --- |
| user_id | int | 

### 戻り値
| 戻り値名 | 型 |
| --- | --- |
| position | int |

### 概要
- ユーザ情報を受け取って、役職IDを返す。

**Comment by Naga564** [comment]
#104 
バックエンドですが、新DB待ちまで来ました

**Comment by Naga564** [comment]
#104 進捗更新しました
