### ISSUE TITLE
未認可書類の切り替え

### ISSUE THREAD

**Issue by magic178** [nkc-cta20-team3/Student-Support-System-reserve#110]
未認可書類を認可した際に次の未認可書類に切り替える機能
データを保持する方法を考える必要がある

**Comment by magic178** [comment]
# 変更すべき要素
- フロントエンド
- - 認可処理を行った後、未認可書類一覧の一番上データを取得したい
  - 書類を認可した際に「次の未認可書類に遷移する」ボタンを押したとき、document_idを取得し、未認可書類を出力する
  - Readdocumentの変更により、恐らく今まで取得出来ていたデータが正しく出力できない恐れがあるため、修正
 -  現状
  - 正しくdocument_idのデータを取得できていないためエラーが出る。
  - document_acceptの181行目～で恐らくデータを取得しているのだが、正直どこをどう書き換えれば良いのか分からない。
- バックエンド 
  - Readdocumentの引数の中身を変更する

**Comment by Naga564** [comment]
次回原因を突き止め、その対策を考えてください

**Comment by Naga564** [comment]
対策が抽象的な気がします
もっと具体的に作業内容をすり合わせる必要があると思います

**Comment by magic178** [comment]
suzukikaito244さんと話し合った結果、フロントのみで解決出来そうとのことだった。ダイアログボックスで書類を認可した際、未認可書類リストの上から1つ目の書類を取得するため、正しいdocument_idを取得し、表示したい。しかし、自分の技術不足でコードをどこをどう変えれば正しく動作するのかが現状不明瞭。

**Comment by Naga564** [comment]
フロントのみで解決できる問題ですか？

**Comment by Naga564** [comment]
具体的に学習するのに期間はどれくらいかかるといった試算はありますか？

**Comment by magic178** [comment]
suzukikaito244さん曰くそれでやってみて欲しい
とのことでした

**Comment by magic178** [comment]
現状もう少し時間は欲しいですが、正直手詰まり感はいがめないのでヘルプが欲しいです。

**Comment by Naga564** [comment]
現状把握のためやるべきタスク一覧が欲しいです
できればやる人とセットで記述し、フロント、バック、その他の分類もお願いしたいです

**Comment by magic178** [comment]
# タスク
- フロントエンド
  - 未認可書類リストの上から1つ目のdocument_idを取得する。
  - 取得したデータをダイアログボックスで書類を認可した際の画面遷移で書類を表示する
- バックエンド
  - document_idを未認可リストの次のidを指定できるような引数を作る

**Comment by Naga564** [comment]
バックエンドの作業はありますか？

**Comment by Naga564** [comment]
その方法だとバックエンドは作業が必要ないように思えます。
理由は次のidをフロント側で呼び出せば実現できるからです

**Comment by Naga564** [comment]
全体的に対策の甘さを感じます。明日時間をとって、対処します

**Comment by Naga564** [comment]
もう一度処理や実装すべきことを考え直しました。
来週の月曜に完成し、予備日として火曜日を取ります
