### ISSUE TITLE
未認可リスト画面切り替えバックエンド

### ISSUE THREAD

**Issue by suzukikaito244** [nkc-cta20-team3/Student-Support-System-reserve#113]

**Comment by Naga564** [comment]
# API仕様

## NextDocument

## 引数(旧環境)
| 引数名 | 型 |
| ---- | ---- |
| teacher_id | int |
    
## 戻り値(旧環境)
| 戻り値名 | 型 |
| ---- | ---- |
 document_id | int 
 request_id | time 
 student_id | int 
 class_name | string 
 student_name | string 
 start_date | time 
 start_flame | int
 end_date | time
 end_flame | int
 location | string
 student_comment | string
 teacher_comment | string

## 仕様
- 教員IDを受け取る
- 教員IDから役職IDを検索する
- その役職IDと教員IDをもとに認可リストを取得する(ReadAuth)
- その認可リストの1番目のdocument_id(最も小さい)の書類を表示する(ReadDocument)

## 補足
- APIからAPIを呼び出せば、比較的簡単に実装できそう
