### ISSUE TITLE
未認可書類の切り替え フロントエンド

### ISSUE THREAD

**Issue by magic178** [nkc-cta20-team3/Student-Support-System-reserve#114]

**Comment by Naga564** [comment]
# フロント作業内容
- teacher_idを未認可リストページから認可ページに持ってくる
    - 最悪できなかったら直接値を埋め込んでもいい
        - 新環境だとuser_idをページで保持できるから
- 認可/却下時の動作
    - 「次へ」を押したとき
        - 「NextDocument」APIを呼び出す
        - 結果に応じてページの要素を変更する
    - 「戻る？」を押したとき
        - 未認可リストページに遷移する
- ホップアップの修正
    - OK、キャンセルの文言を変える

**Comment by magic178** [comment]
teacher_idを未認可リストページから認可ページに持ってくるタスクだけできていない

**Comment by magic178** [comment]
teacher_idは現状直打ち

**Comment by magic178** [comment]
### 仕様
- 教員IDを受け取る
- 教員IDから役職IDを検索する
- その役職IDと教員IDをもとに認可リストを取得する(ReadAuth)
- その認可リストの1番目のdocument_id(最も小さい)の書類を表示する(ReadDocument)←この値が帰ってくる

### 補足
- APIからAPIを呼び出せば、比較的簡単に実装できそう

## フロント作業内容
- teacher_idを未認可リストページから認可ページに持ってくる(埋め込んだ)
    - 最悪できなかったら直接値を埋め込んでもいい
        - 新環境だとuser_idをページで保持できるから
- 認可/却下時の動作
    - 「次へ」を押したとき
        - 「NextDocument」APIを呼び出す
        - 結果に応じてページの要素を変更する
    - 「戻る？」を押したとき
        - 未認可リストページに遷移する
- ホップアップの修正
    - OK、キャンセルの文言を変える
