### ISSUE TITLE
中間発表用機能実装

### ISSUE THREAD

**Issue by Naga564** [nkc-cta20-team3/Student-Support-System-reserve#129]
# Todo
## フロントエンド
- [ ] 学生用公欠届提出画面の作成
- [x] 学生用公欠届確認画面の作成
- [ ] 見やすさの調整

## バックエンド
- [x] 学生用公欠届取得APIの作成
- [ ] 公欠届提出用APIの作成

## その他

**Comment by Naga564** [comment]
公欠届提出の処理まわりがうまくいっていません
フォームの作成方法がよくわかりません

先にバックエンドで登録するAPIを作ろうかと思っています

**Comment by TYT77** [comment]
中間発表は終わったためこのIssueを閉じます
