### ISSUE TITLE
画面作成

### ISSUE THREAD

**Issue by magic178** [nkc-cta20-team3/Student-Support-System-reserve#131]
- ログイン前画面作成
- ログイン後トップ画面(学生・教員・管理者)
    - 学生
    - 教員
    - 管理者
- 学生用書類提出画面
- 教員用書類認可画面(未認可リスト+認可)
- 管理者用ユーザー登録画面
- 管理者用ユーザー編集画面

**Comment by toymayt5167** [comment]
Figmaの画面をそのままコードにできるVuetifyを利用予定
脇田君がFigmaの画面を完成次第、手が空いてる組(田橋 or 遠山)がコード化

**Comment by magic178** [comment]
旧環境のため作業スペースを#155画面設計に移動

**Comment by magic178** [comment]
用済み
