### ISSUE TITLE
フロント内部機能

### ISSUE THREAD

**Issue by otake030** [nkc-cta20-team3/Student-Support-System-reserve#132]

**Comment by otake030** [comment]
少し混乱して何個か間違えて作ったブランチがあります
998 と　132はミスったものなので一応調べた限りの消去処置をとったけど有識者が気付いた場合消去処理を完全にこなしていただければありがたいです

**Comment by otake030** [comment]
135-internal-fanctionが消されていたので後続のブランチとして201-internal-fanctionを作成しました

**Comment by TYT77** [comment]
フロントエンド側の内部実装が完了にすんではいませんが、
すみわけのためにいったんこちらのIssueはクローズします。

このブランチで作業する予定だったものは7割実装済みです。
