### ISSUE TITLE
公欠届リスト取得API

### ISSUE THREAD

**Issue by suzukikaito244** [nkc-cta20-team3/Student-Support-System-reserve#139]
# 仕様・処理
  - 該当教員の未認可リスト及び学生の簡単な提出書類を取得する。
  - 引数として学内識別番号を受け取る
  - 引数の学内識別番号をチェックする
      - 担任であった場合、担任クラスの未認可リストを取得する
      - 主任以上であった場合、認可すべき未認可リストすべてを取得する
      - 学生であった場合、自身が提出したデータを取得する
  - 取得する「未認可リスト」とは、書類のステータスが(役職ID-1)と一致するものである
  - 戻り値として書類のリストを返却する
      - JSON形式にして返却する

**Comment by Naga564** [comment]
学生にも対応させました。
つまるところ完成しました

**Comment by Naga564** [comment]
# 確認コマンド
## コマンド
- curl -X POST -H "Content-Type: application/json" -d '{"user_id": 1}' http://localhost:8080/api/ral
  - 学生確認
- curl -X POST -H "Content-Type: application/json" -d '{"user_id": 2}' http://localhost:8080/api/ral
  - 教員確認
