### ISSUE TITLE
ユーザ登録API

### ISSUE THREAD

**Issue by Naga564** [nkc-cta20-team3/Student-Support-System-reserve#140]
# 仕様・処理
- 新規のユーザを登録する
- 引数として受け取った学内識別番号を精査
    - 管理者かどうかを確認する
- 入力されたユーザ情報をDBに格納する
    - Create文を発行
    - UserIDは登録しない
        - Firebaseに関連してくる項目のため

**Comment by suzukikaito244** [comment]
管理者の判定以外の機能完成
