### ISSUE TITLE
公欠届詳細情報取得API

### ISSUE THREAD

**Issue by suzukikaito244** [nkc-cta20-team3/Student-Support-System-reserve#141]
# 仕様・処理
  - 書類の詳細情報を表示する
  - 引数として書類IDと学内識別番号を受け取る
  - 学内識別番号を用いて、そのユーザが存在するかを確認する
      - 確認できない場合、エラーを返す
      - 存在した場合、以下の処理を実行する
  - 書類IDを用いて、DBにクエリを送信する
      - 書類の詳細情報を受け取る
  - 戻り値として書類の詳細情報を返却する
      - JSON形式にして返却する

**Comment by Naga564** [comment]
git checkout 141-ReadDocument-Backend
