### ISSUE TITLE
ユーザ編集API

### ISSUE THREAD

**Issue by Naga564** [nkc-cta20-team3/Student-Support-System-reserve#142]
# 仕様・処理
- ユーザデータを編集する
    - ここでのユーザは**学生・教員・管理者すべて**を指す
- 引数の学内識別番号が管理者であるかを確認する
    - 管理者ではないときはエラー
- 引数をもとにデータベースのデータを更新する
    - 新たに管理者を増やすことはできない(チェック)
- 戻り値として成否結果を返却する

**Comment by suzukikaito244** [comment]
管理者の判定
管理者の追加以外の機能完成
