### ISSUE TITLE
公欠届認可処理API

### ISSUE THREAD

**Issue by suzukikaito244** [nkc-cta20-team3/Student-Support-System-reserve#143]
# 仕様・処理
  - 該当書類を認可された状態にする
  - 引数として書類IDを受け取る
      - 誰の公欠届かを確認する
  - 引数として学内識別番号を受け取る
      - 受け取った書類が、認可するのに適切な教員であるかを確認する
          - ステータス = 役職ID - 1
          - 担任の場合、所属クラスが同じであるかも確認
          - そもそも教員でない場合はエラーを返す
  - 引数として教員コメントを受け取る
      - 教員コメントが入力されているか確認する
  - 認可処理を行う
      - UPDATE文で、書類ステータスと教員コメントを更新する
  - 最後に成否を戻り値として返す。

**Comment by Naga564** [comment]
GitBashで実行

curl -X POST -H "Content-Type: application/json" -d '{"document_id": 1,"user_number": 20206000,"teacher_comment": "This is a sample comment."}' http://localhost:8080/api/ua

**Comment by Naga564** [comment]
所属クラスのチェックは現状できていない
テストデータの見直しがあればできそう

**Comment by Naga564** [comment]
# テストコマンド
## コマンド
- curl -X POST -H "Content-Type: application/json" -d '{"document_id": 1,"user_id": 2,"teacher_comment": "This is a sample comment."}' http://localhost:8080/api/ua
  - 成功例
- curl -X POST -H "Content-Type: application/json" -d '{"document_id": 1,"user_id": 3,"teacher_comment": "This is a sample comment."}' http://localhost:8080/api/ua
  - 権限エラー
## 注意点
- ステータスエラーについては、phpmyadminでステータスを操作して確認する
- コマンドを試した後にステータスが変化しているので連続で実行すると結果が変わる
