### ISSUE TITLE
公欠届却下処理API

### ISSUE THREAD

**Issue by suzukikaito244** [nkc-cta20-team3/Student-Support-System-reserve#144]
# 仕様・処理
  - 該当書類を却下(再提出)された状態にする
  - 引数として書類IDと学内識別番号を受け取る
      - 却下する書類と教員が適切な関係にあるかを確認する
  - 引数として教員コメントを受け取る
      - 値が入力されているかを確認する
      - 却下する時にコメントが無かった場合、却下しない
  - 書類を却下する
      - Statusを-1にする
      - 教員コメントを更新する
  - 戻り値として成否の結果を返す

**Comment by Naga564** [comment]
書類と認可/却下者の整合性を確認する以外は完成

**Comment by Naga564** [comment]
curl -X POST -H "Content-Type: application/json" -d '{"document_id": 1,"user_number": 1,"teacher_comment": "Rejected"}' http://localhost:8080/api/ra

**Comment by Naga564** [comment]
user_idが引数になくて、認証周りができない可能性がありますが、どうしましょう

**Comment by Naga564** [comment]
# テストコマンド
## コマンド
- curl -X POST -H "Content-Type: application/json" -d '{"document_id": 1,"user_id": 1,"teacher_comment": "Rejected"}' http://localhost:8080/api/ra
  - 権限エラー
- curl -X POST -H "Content-Type: application/json" -d '{"document_id": 1,"user_id": 2,"teacher_comment": ""}' http://localhost:8080/api/ra
  - コメントエラー
- curl -X POST -H "Content-Type: application/json" -d '{"document_id": 1,"user_id": 2,"teacher_comment": "Rejected"}' http://localhost:8080/api/ra
  - 成功例
