### ISSUE TITLE
バックエンドファイル調整

### ISSUE THREAD

**Issue by Naga564** [nkc-cta20-team3/Student-Support-System-reserve#173]
今あるファイルを学生用・教員用・管理者用に分けます
バックエンドのみ対象です

**Comment by Naga564** [comment]
# ユーザ別メモ
## 学生
- NextDocument
- ReadAuthList
- ReadDocument
- CreateDocument
- ResubmitDocument
- CheckAlarm
- ReadDivision
- ReadAlarm

## 教員
- NextDocument
- ReadAuthList
- ReadDocument
- UpadateAuth
- RejectAuth
- CheckAlarm
- ReadAlarm
## 管理者
- CreateUser
- UpdateUser
- ReadUserList
- ReadUser
- SortUser
- DeleteUser
- (ReadPrepareInformation)

## 全員
- (CheckLogin)

**Comment by TYT77** [comment]
このIssueの内容は解決済みのためクローズします
