### ISSUE TITLE
バックエンド動作確認

### ISSUE THREAD

**Issue by Naga564** [nkc-cta20-team3/Student-Support-System-reserve#175]
ファイル構造修正後のバックエンドの動作確認及び確認コマンドを記載します

**Comment by Naga564** [comment]
# 現状バックエンドファイル構造(apiフォルダ内)
- CheckLogin.go
- **student**
  - NextDocument.go
  - ReadAuthList.go
  - ReadDocument.go
  - CreateDocument.go
  - ResubmitDocument.go
  - CheckAlarm.go
  - ReadDivision.go
  - ReadAlarm.go
- **teacher**
  - NextDocument.go
  - ReadAuthList.go
  - ReadDocument.go
  - UpadateAuth.go
  - RejectAuth.go
  - CheckAlarm.go
  - ReadAlarm.go
- **admin**
  - CreateUser.go
  - UpdateUser.go
  - ReadUserList.go
  - ReadUser.go
  - SortUser.go
  - DeleteUser.go
  - ReadPrepareInformation.go

**Comment by Naga564** [comment]
# 確認コマンド(学生)
- NextDocument
  - curl -X POST -H "Content-Type: application/json" -d '{"document_id":1,"user_id":1,"next_flag":true}' http://localhost:8080/api/student/nd
    - 2番の書類が返却される
- ReadAuthList
  - curl -X POST -H "Content-Type: application/json" -d '{"user_id":1}' http://localhost:8080/api/student/ral
    - ユーザID1の提出した書類2件が返却される
- ReadDocument
- curl -X POST -H "Content-Type: application/json" -d '{"document_id":1,"user_id":1}' http://localhost:8080/api/student/rd
  - ユーザID1の提出した1番の書類が返却される
- CreateDocument
  - curl -X POST -H "Content-Type: application/json" -d '{"user_id":1,"request_at":"2023-11-30","start_time":"2023-12-01 13:00:00","end_time":"2023-12-01 15:00:00","location":"nagoya","student_comment":"testcode","division_id":100}' http://localhost:8080/api/student/cd
    - ユーザID1が新しく公欠届を提出する
- ResubmitDocument
  - curl -X POST -H "Content-Type: application/json" -d '{"document_id":11,"user_id":1,"request_at":"2023-11-29","start_time":"2023-12-01 10:00:00","end_time":"2023-12-01 11:00:00","location":"nagoya","student_comment":"testcode","division_id":100}' http://localhost:8080/api/student/rsd
    - Createで作成した公欠届を再提出する(実行前にあらかじめ、再提出状態にする必要あり)
- CheckAlarm
- curl -X POST -H "Content-Type: application/json" -d '{"user_id":1}' http://localhost:8080/api/student/ca
  - ユーザID1の通知状況(あり/なし)が返却される
- ReadDivision
- curl -X POST -H "Content-Type: application/json" -d '{"user_id":1}' http://localhost:8080/api/student/rdv
  - 公欠届の区分情報を返却する
- ReadAlarm
- curl -X POST -H "Content-Type: application/json" -d '{"user_id":1}' http://localhost:8080/api/student/al
  - ユーザID1の通知詳細(表示をするために必要な情報)を返却する

**Comment by Naga564** [comment]
CreateDocumentとResubmitDocumentは引数の見直しが必要なので、いったん保留です

**Comment by Naga564** [comment]
# 確認コマンド(教員)
- NextDocument.go
  - curl -X POST -H "Content-Type: application/json" -d '{"document_id":2,"user_id":10,"next_flag":true}' http://localhost:8080/api/teacher/nd
    - 2番の書類の次に認可すべき書類情報を返却する
- ReadAuthList.go
  - curl -X POST -H "Content-Type: application/json" -d '{"user_id":10}' http://localhost:8080/api/teacher/ral
    - 教員が認可すべき書類の情報を返却する
- ReadDocument.go
  - curl -X POST -H "Content-Type: application/json" -d '{"document_id":1,"user_id":10}' http://localhost:8080/api/teacher/rd
    - 1番の書類の情報を取得する
- UpadateAuth.go
  - curl -X POST -H "Content-Type: application/json" -d '{"document_id":2,"user_id":10,"teacher_comment":"testcode"}' http://localhost:8080/api/teacher/ua
    - 2番の書類を認可された状態にする
- RejectAuth.go
  - curl -X POST -H "Content-Type: application/json" -d '{"document_id":2,"user_id":10,"teacher_comment":"testcode"}' http://localhost:8080/api/teacher/ra
    - 2番の書類を却下された状態にする
- CheckAlarm.go
  - curl -X POST -H "Content-Type: application/json" -d '{"user_id":10}' http://localhost:8080/api/teacher/ca
    - 教員の通知の有無を返却する
- ReadAlarm.go
  - curl -X POST -H "Content-Type: application/json" -d '{"user_id":10}' http://localhost:8080/api/teacher/al
    - 通知の詳細情報を取得する

**Comment by Naga564** [comment]
# 確認コマンド(管理者)
- CreateUser.go
  - curl -X POST -H "Content-Type: application/json" -d '{"user_id":16,"user_name":"田中太郎","user_number":20202020,"post_id":1,"class_id":117,"mail_address":"test@gmail.com"}' http://localhost:8080/api/admin/cu
  - 学生の田中太郎ユーザが作成される
- UpdateUser.go
  - curl -X POST -H "Content-Type: application/json" -d '{"user_id":16,"update_user_id":18,"user_name":"田中次郎","user_number":22222222,"post_id":2,"class_id":117,"mail_address":"tester@gmail.com"}' http://localhost:8080/api/admin/uu
  - CreateUserで作成したユーザの情報を編集する
- ReadUserList.go
  - curl -X POST -H "Content-Type: application/json" -d '{"user_id":16}' http://localhost:8080/api/admin/rul
    - ユーザのリストを返却する
- ReadUser.go
  - curl -X POST -H "Content-Type: application/json" -d '{"access_user_id":16,"target_user_id":1}' http://localhost:8080/api/admin/ru
      - ユーザの詳細情報を返却する
- SortUser.go
  - curl -X POST -H "Content-Type: application/json" -d '{"user_id":16,"search_string":"60"}' http://localhost:8080/api/admin/su
    - 学内識別番号(学生番号)に「60」を含むユーザのリストを返却する
- DeleteUser.go
  - curl -X POST -H "Content-Type: application/json" -d '{"access_user_id":16,"target_user_id":18}' http://localhost:8080/api/admin/du
    - CreateUserで作成したユーザを削除する(無効化する)
- ReadPrepareInformation.go
  - 未作成(管轄外)

**Comment by Naga564** [comment]
今ある分は完了

**Comment by TYT77** [comment]
上記の動作確認方法は、JWT認証を有効化した場合には、試行不可です。
コード側でミドルウェアの設定部分をコメントアウトしてから試行してください。

また、このIssueの内容は完了しているためクローズします
