### ISSUE TITLE
日付取得のフォーマット問題

### ISSUE THREAD

**Issue by Naga564** [nkc-cta20-team3/Student-Support-System-reserve#176]

**Comment by Naga564** [comment]
# 影響範囲
- 引数や戻り値に日付を含むものまとめ
## 学生
### 引数
- [x] CreateDocument.go
- [x] ResubmitDocument.go
### 戻り値
- [x] NextDocument.go
- [x] ReadDocument.go
- [x] ReadAlarm.go
## 教員
### 引数
- なし
### 戻り値
- [x] NextDocument.go
- [x] ReadDocument.go
## 管理者
### 引数
- なし
### 戻り値
- なし

**Comment by TYT77** [comment]
紐づけたプルリクが解決しているようなのでIssueを閉じます
