### ISSUE TITLE
バックエンドFireBase連携

### ISSUE THREAD

**Issue by Naga564** [nkc-cta20-team3/Student-Support-System-reserve#180]
# ToDo
- [ ] FireBaseを用いたJWT認証を実装
  - [ ] ミドルウェアの実装
- [ ] FireBaseと関連のあるAPIの実装
  - [ ] CheckLogin
  - [ ] ReadPrepareInformation
- [x] その他API実装
- [x] ログインしたユーザの役職取得

**Comment by Naga564** [comment]
# 追加API
- ReadPost
  - 役職一覧取得
- ReadClass
  - クラス一覧取得
- ReadUserPost
  - ログイン者役職取得

**Comment by TYT77** [comment]
「 FireBaseと関連のあるAPIの実装」のみ未実装ですが、
別のIssueを立てて、そこでまとめて作業するため、
それ以外が完了しているこちらのIssueはクローズします。
