### ISSUE TITLE
学内発表用資料作成

### ISSUE THREAD

**Issue by Naga564** [nkc-cta20-team3/Student-Support-System-reserve#186]
# Todo
- プレゼンについて
 - [ ] プレゼン作成
 - [ ] 発表原稿作成
 - [ ] 発表練習
- 資料について
 - [ ] 使用言語について
 - [ ] 開発の流れ
 - [ ] 使用技術
 - [ ] 学び

**Comment by Naga564** [comment]
使用言語の資料はPythonについての記述以外完成
あとは内容が薄いのを修正

**Comment by TYT77** [comment]
学内発表は終了しました。次は本番発表です。
すみわけのためにこちらのIssueはクローズします。
