### ISSUE TITLE
ログイン情報を保持する機能

### ISSUE THREAD

**Issue by otake030** [nkc-cta20-team3/Student-Support-System-reserve#54]

**Comment by TYT77** [comment]
ログイン情報の取得までは完了していることを確認しました。
これから新しく用意するAPIを、ログイン時に叩くことでユーザーの詳細情報を取得、保持するように随時更新してください。

**Comment by TYT77** [comment]
新しく用意する予定のAPIも作成が凍結されたため、クローズします。
