### ISSUE TITLE
GitHub Actionを使用したCI/CD環境を構築する(lambda)

### ISSUE THREAD

**Issue by toymayt5167** [nkc-cta20-team3/Student-Support-System-reserve#83]
Main Branchにpull requestを発行し、mergeされた際にlambdaにデプロイされるように設定する

**Comment by toymayt5167** [comment]
現在難航中のため全体が一通り完成後実装する

**Comment by Naga564** [comment]
終わったら一旦devlopの方にmergeしておいてください。

**Comment by toymayt5167** [comment]
問題が解決したのでGASとともに実装する
問題としてはgithub secretに登録した名前とコードとの名前が違った

**Comment by toymayt5167** [comment]
GASのCI/CDは完成
今週中にはlambdaのCI/CDを完成させる

**Comment by toymayt5167** [comment]
lambdaの方の進捗
・形だけは出来た
・あとはAWS側のロールの問題だと思っている
・発表までには出来る

**Comment by toymayt5167** [comment]
CICDは終わっているのでこのissueはいりません
