### ISSUE TITLE
第2回中規模リファクタリングの実施

### ISSUE THREAD

**Issue by TYT77** [nkc-cta20-team3/Student-Support-System-reserve#94]
DB構造やテストデータの変更、各種ブランチごとのすり合わせを兼ねて中規模なリファクタリングを実施しています。
また、この際に以下の項目を実施します。
- DB構造の変更
- 既存のテストデータの更新
- firebaseとmysqlのデータ連携のためのバックエンド実装
- ユーザーの詳細情報を取得するAPIの実装
- 提出した書類の情報を取得するAPIの更新と、呼び出し側の実装
- リポジトリ名の変更

**Comment by TYT77** [comment]
追加で、readmeを更新することにしました

**Comment by TYT77** [comment]
### Todo
- [x] Readmeの更新
- [x] DB構造の変更
- [x] 既存のテストデータの更新
- [ ] firebaseとmysqlのデータ連携のためのバックエンド実装
- [ ] ユーザーの詳細情報を取得するAPIの実装
- [ ] 提出した書類の情報を取得するAPIの更新と、呼び出し側の実装
- [x] リポジトリ名の変更
- [x] Go側からDBに接続する際の接続文字列に環境変数を使用するようにする
- [x] 現行のAPIの更新(ReadDocument)
- [x] 現行のAPIの更新(ReadAuthList)
- [x] 現行のAPIの更新(UpdateAuth)

### Todo外
- [x] Goアプリケーションのホットリロードを有効にする。

**Comment by TYT77** [comment]
追加
Go側からDBに接続する際の接続文字列に環境変数を使用するようにする

**Comment by Naga564** [comment]
できれば、TODOに対応している作業したことを具体的に教えてほしいです(文法)

例)
Readmeの更新
使用法の記述を見直した(現在の手順に更新した)
DB構造の変更
SSOに対応させるために、uid列をuser表に追加した

**Comment by Naga564** [comment]
できればでいいです。
最低でも変更後には絶対書いてください
属人化が発生してネックになってしまうので

**Comment by Naga564** [comment]
DB構造気になったこと
・user表,user_idはユニーク制約?
・post_idはnot nullを入れる？
→多分入れるべき

**Comment by TYT77** [comment]
現在、このIssueは一時的に凍結しています。
ですが、全体の進捗が進んだ際に解凍される可能性があるのでOpenのまま残しておきます。

**Comment by TYT77** [comment]
> ・user表,user_idはユニーク制約?
＞・post_idはnot nullを入れる？

どちらも指摘に対して該当する列を見つけきれませんでした。

**Comment by Naga564** [comment]
多分昔の表を参照してました

**Comment by Naga564** [comment]
DB構造はリファクタリングの有無にかかわらず変更する必要があるため早急に対応お願いします

**Comment by TYT77** [comment]
構造のみ対応済みです。
テストデータは...順次対応します

**Comment by TYT77** [comment]
事後報告
Goアプリケーションのホットリロードを有効にしました。

**Comment by Naga564** [comment]
https://github.com/nkc-cta20-team3/N-suma/issues/94#issuecomment-1598745474

これについて、現行のAPIすべての修正+新しく追加予定のAPIについても対応しました。

**Comment by Naga564** [comment]
https://github.com/nkc-cta20-team3/N-suma/issues/94#issuecomment-1598745474

これについて
ユーザーの詳細情報を取得するAPIの実装
提出した書類の情報を取得するAPIの更新と、呼び出し側の実装

バックエンドで少し仕様がわかれば僕も対応できます
