### ISSUE TITLE
中間報告発表準備

### ISSUE THREAD

**Issue by Naga564** [nkc-cta20-team3/Student-Support-System-reserve#97]
- 7/12か7/19の中間発表の資料作成
- 人数：3人以内

**Comment by Naga564** [comment]
Naga564は監修する
yukkeは監修するかも？

**Comment by Naga564** [comment]
7月に入ったら作成予定(7/3~)

**Comment by toymayt5167** [comment]
Googleスライドを作成し、全体の流れだけは形にした。
後は暇なときにでも、全体で話して話す内容を考える。

**Comment by TYT77** [comment]
中間発表に関して現状のシステムを修正するためのブランチ等も紐づけるためIssue名を変更
